example/project/urls.py
from django.contrib import admin
from django.urls import include, path

from unicorn.components.hello_world import HelloWorldView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("www.urls")),
    # Include django-unicorn urls
    path("unicorn/", include("django_unicorn.urls")),
    path("test", HelloWorldView.as_view(), name="test"),
]

example/www/urls.py
from django.urls import path

from example.unicorn.components.direct_view import DirectViewView
from example.unicorn.components.redirects import RedirectsView
from example.www import views


app_name = "www"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "direct-view",
        DirectViewView.as_view(),
        name="direct-view",
    ),
    path(
        "redirects",
        RedirectsView.as_view(),
        name="redirects",
    ),
    path("<str:name>", views.template, name="template"),
]

example/books/models.py
from django.db import models


class Book(models.Model):
    TYPES = ((1, "Hardcover"), (2, "Softcover"))
    title = models.CharField(max_length=255)
    date_published = models.DateField()
    type = models.IntegerField(choices=TYPES, default=1)


class Author(models.Model):
    name = models.CharField(max_length=1024)
    books = models.ManyToManyField(Book)

example/coffee/models.py
import uuid

from django.db import models


class Flavor(models.Model):
    name = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=models.SET_NULL)
    float_value = models.FloatField(blank=True, null=True)
    decimal_value = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=2)
    uuid = models.UUIDField(default=uuid.uuid4)
    datetime = models.DateTimeField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    duration = models.DurationField(blank=True, null=True)

    def __str__(self):
        return self.name


class Favorite(models.Model):
    is_favorite = models.BooleanField(default=False)
    flavor = models.OneToOneField(Flavor, on_delete=models.CASCADE)


class Taste(models.Model):
    name = models.CharField(max_length=255)
    flavor = models.ManyToManyField(Flavor)


class Origin(models.Model):
    name = models.CharField(max_length=255)
    flavor = models.ManyToManyField(Flavor, related_name="origins")


class NewFlavor(Flavor):
    new_name = models.CharField(max_length=255)

example/unicorn/components/models.py
from django_unicorn import QuerySetType, UnicornView
from example.coffee.models import Flavor, Taste


class ModelsView(UnicornView):
    flavor: Flavor = None
    flavors: QuerySetType[Flavor] = Flavor.objects.none()

    def mount(self):
        self.flavor = Flavor()
        self.refresh_flavors()

    def refresh_flavors(self):
        self.flavors = Flavor.objects.all().order_by("-id")[:2]

    def save_flavor(self):
        self.flavor.save()
        self.flavor = Flavor()
        self.refresh_flavors()

    def save(self, flavor_idx: int):
        flavor_data = self.flavors[flavor_idx]
        flavor_data.save()

    def delete(self, flavor_to_delete: Flavor):
        flavor_to_delete.delete()
        self.refresh_flavors()

    def available_flavors(self):
        return Flavor.objects.all()

    def available_tastes(self):
        return Taste.objects.all()

    def model_typehint(self, flavor: Flavor):
        print(flavor)

    class Meta:
        javascript_exclude = ("flavor.taste_set",)

example/unicorn/forms.py
from django import forms


class ValidationForm(forms.Form):
    text = forms.CharField(min_length=3, max_length=10)
    date_time = forms.DateTimeField()
    number = forms.IntegerField()
    email = forms.EmailField()

example/www/views.py
from django.http.response import Http404
from django.shortcuts import render
from django.template.exceptions import TemplateDoesNotExist


def index(request):
    return render(request, "www/index.html")


def template(request, name):
    try:
        return render(request, f"www/{name}.html", context={"example": "test"})
    except TemplateDoesNotExist:
        raise Http404

example/unicorn/templates/unicorn/direct-view.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

<div unicorn:view>
  <h2>Direct View</h2>

  <input u:model="name" />
  {{ name }}
</div>

{% endblock content %}

example/unicorn/templates/unicorn/hello-world-test.html
<div>
  <button unicorn:click="$reset">Reset the component</button>
  <button onclick="document.getElementById('name').value = 'asdf';">Plain JS set value on key1</button>
  <button onclick="Unicorn.trigger('unicorn.components.hello_world.HelloWorldView', 'key1')">Trigger key1</button>
  <br />
  <br />

  <label></label>
  <input unicorn:model="name" type="text" id="name" unicorn:key="key1">

  Hello, {{ name|default:'World' }}!

  <div>
    Request path context variable: '{{ request.path }}'
  </div>

  <script type="application/javascript">
    window.addEventListener('DOMContentLoaded', (event) => {
      Unicorn.addEventListener('updated', (component) => console.log('got updated', component));
    });

  </script>
</div>

example/unicorn/templates/unicorn/html-inputs.html
<div>
  <div id="boolean-toggles-id">
    <h2>Checkbox</h2>
    <input type="checkbox" unicorn:model="is_checked" id="check">
    {% if is_checked %}Yes! 🦄{% else %}Nope 🙁{% endif %}
  </div>

  <div unicorn:key="boolean-toggles-key">
    <h2>Boolean Toggles</h2>
    {% if another_check %}Checked ✅{% else %}Not checked ❎{% endif %}
    <br />
    <button unicorn:click="$toggle('is_checked', 'another_check')">Toggle booleans (normal)</button><br />
    <button unicorn:click="$toggle('is_checked', 'another_check')" u:partial.key="boolean-toggles-key">Toggle booleans
      (partial.key)</button>
    <button unicorn:click="$toggle('is_checked', 'another_check')" u:partial.id="boolean-toggles-id">Toggle booleans
      (partial.id)</button><br />
    <button unicorn:click="$toggle('is_checked', 'another_check')" u:partial.id="boolean-toggles-id"
      u:partial.key="boolean-toggles-key">Toggle booleans (multiple partials)</button><br />
    <button unicorn:click="$toggle('is_checked', 'another_check')" u:partial="boolean-toggles-id">Toggle booleans
      (partial boolean-toggles-id)</button>
    <button unicorn:click="$toggle('is_checked', 'another_check')" u:partial="boolean-toggles-key">Toggle booleans
      (partial boolean-toggles-key)</button>
  </div>

  <div>
    <h2>Select</h2>
    <select unicorn:model="thing" id="select">
      <option>🐶</option>
      <option>🐙</option>
      <option>👾</option>
    </select>

    <p>
      Hi {{ thing }}
    </p>
  </div>

  <div>
    <h2>Default Select</h2>
    <select unicorn:model="flavor" id="select-default">
      <option value="cool">cool</option>
      <option value="">-- select --</option>
      {% for flavor in flavors %}
      <option value="{{ flavor }}">{{ flavor }}</option>
      {% endfor %}
    </select>

    <p>
      Hi {{ flavor }}
    </p>
  </div>

  <div>
    <h2>Multiple select</h2>
    <select unicorn:model="things" id="select-multiple" multiple>
      <option value="doggo">🐶</option>
      <option value="octopus">🐙</option>
      <option value="alien">👾</option>
    </select>

    <p>
      Howdy {{ things|join:", " }}
    </p>
  </div>

  <div>
    <h2>Radio buttons</h2>
    <input type="radio" unicorn:model="pie" name="pie" value="blueberry"> Blueberry</input><br />
    <input type="radio" unicorn:model="pie" name="pie" value="apple"> Apple</input><br />
    <input type="radio" unicorn:model="pie" name="pie" value="cherry"> Cherry</input>

    <p>
      Delicious {{ pie|upper }} pie
    </p>
  </div>

  <div>
    <h2>Textarea</h2>
    <textarea unicorn:model="paragraph" id="textarea"></textarea>

    <p>
      Number of characters: {{ paragraph|length }}

      <button unicorn:click="paragraph=''">Clear textarea</button>
    </p>
  </div>

  <div>
    <h2>Typeahead</h2>
    <input type="text" unicorn:model="state" placeholder="State name" id="typeahead"></input>

    <p>
      Matching states:

      {% if states %}
      <ul>
        {% for s in states %}
        <li>{{ s }}</li>
        {% endfor %}
      </ul>

      <button unicorn:click="clear_states">Clear States</button>
      {% endif %}
    </p>
  </div>
</div>

example/unicorn/templates/unicorn/js.html
{% load static %}

<div>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script>
    function callAlert(name) {
      alert("hello, " + name);
    }

    var HelloJs = (function () {
      var self = {};

      self.hello = function (name) {
        alert("Hello " + name)
      }

      return self;
    }());
  </script>

  <h3>Visibility</h3>
  <div unicorn:key="visibility">
    <span unicorn:visible.threshold-25.debounce-1000="increase_counter" unicorn:partial="visibility">
      Number of times this span was scrolled into view: {{ scroll_counter }}
    </span>
  </div>

  <h3>Call JavaScript</h3>
  <button unicorn:click="call_javascript">Component view calls JavaScript</button>
  <button unicorn:click="call_javascript_module">Component view calls JavaScript module</button>

  <div>
    <h3>
      <code>javascript_exclude states</code>
    </h3>
    {% for state in states %}
    {{ state }}
    {% endfor %}
  </div>

  <h3>Select2</h3>

  <div u:ignore>
    <select unicorn:model="selected_state" class="form-control" id="select2-example" required
      onchange="Unicorn.call('js', 'select_state', this.value, this.selectedIndex);">
      {% for state in states %}
      <option value="{{ state }}">{{ state }}</option>
      {% endfor %}
    </select>

    States (in ignored div): {{ states }}
  </div>

  selected_state: {{ selected_state }}

  <script>
    $(document).ready(function () {
      $('#select2-example').select2();
    });
  </script>

  <div>
    States (not in ignored div): {{ states }}<br />
    <button type="submit" u:click="change_states">Change states</button>
  </div>

  <div>
    <input type="text" u:model="select2_datetime" />
    <button type="submit" u:click="get_now">Get now</button>
    <div>
      select2_datetime: {{ select2_datetime }}
    </div>
  </div>

  <div>
    <button u:click="$toggle('load_js')">Toggle {{ load_js }}</button>
    <p>load_js: {{ load_js }}
    </p>
    {% if load_js %}
    <script src="{% static "js/alert.js" %}"></script>
    <script src="{% static "js/console.js" %}"></script>
    {% endif %}
  </div>
</div>

example/unicorn/templates/unicorn/models.html
<div>
  <style>
    .dirty {
      border: red 1px solid !important;
    }

  </style>

  <div>
    <h3>Using unicorn:model with Django models</h3>

    <div>
      <div>
        <label>Name</label>
        <input type="text" unicorn:model="flavor.name"></input>
      </div>

      <div>
        <label>Label</label>
        <input type="text" unicorn:model="flavor.label"></input>
      </div>

      <button unicorn:click="save_flavor">save_flavor</button>

      {% for flavor in flavors %}
      <div>
        <h4>{{ flavor.pk }}</h4>
        <label>Name</label>
        <input type="text" unicorn:model="flavors.{{ forloop.counter0 }}.name" u:dirty.class="dirty"></input>
        {{ flavor.name }}
        <br />

        <label>Label</label>
        <input type="text" unicorn:model="flavors.{{ forloop.counter0 }}.label" u:dirty.class="dirty"></input>
        {{ flavor.label }}
        <br />

        <label>Float</label>
        <input type="text" unicorn:model="flavors.{{ forloop.counter0 }}.float_value"></input>
        {{ flavor.float_value }}
        <br />

        <label>Decimal value</label>
        <input type="text" unicorn:model="flavors.{{ forloop.counter0 }}.decimal_value"></input>
        {{ flavor.decimal_value }}
        <br />

        <label>Parent</label>
        <select unicorn:model="flavors.{{ forloop.counter0 }}.parent">
          <option value="">n/a</option>
          {% for available_flavor in available_flavors %}
          <option value="{{ available_flavor.pk }}">{{ available_flavor.name }}</option>
          {% endfor %}
        </select>
        {{ flavor.parent.name }}
        <br />

        <label>Taste</label>
        <select unicorn:model="flavors.{{ forloop.counter0 }}.taste_set" multiple>
          {% for available_taste in available_tastes %}
          <option value="{{ available_taste.pk }}">{{ available_taste.name }}</option>
          {% endfor %}
        </select>

        <ul>
          {% for taste in flavor.taste_set.all %}
          <li>{{ taste.name }}</li>
          {% endfor %}
        </ul>
        <br />

        <button unicorn:click="save({{ forloop.counter0 }})">save(flavor_idx)</button>
        <button unicorn:click="delete({{ flavor.pk }})">delete(flavor.pk)</button>
        <button u:click="model_typehint({{ flavor.pk }})">model_typehint(flavor.pk)</button>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

example/unicorn/templates/unicorn/nested/favorite.html
<div>
  <input type="checkbox" unicorn:model="model.is_favorite" />
</div>

example/unicorn/templates/unicorn/nested/filter.html
<!-- filter.html -->
<div>
  Filter: <input type="text" unicorn:model="search" /><br />
  Search: "{{ search }}"
</div>

example/unicorn/templates/unicorn/nested/row.html
<!-- row.html -->
{% load unicorn %}
<tr>
  <td>
    {% if is_editing %}
    <input type="text" unicorn:model.defer="model.name" />
    {% else %}
    {{ model.name }}
    {% endif %}
  </td>
  <td>
    {% if is_editing %}
    <input type="text" unicorn:model.defer="model.label" />
    {% else %}
    {{ model.label }}
    {% endif %}
  </td>
  <td>
    {% if is_editing %}
    <input type="text" unicorn:model.defer="model.datetime" />
    {% elif model.datetime %}
    {{ model.datetime }}
    {% else %}
    n/a
    {% endif %}
  </td>
  <td{% if is_updated_by_child %} style="background-color: #2b8cee;" {% endif %}>
    {% unicorn 'nested.favorite' key=model.favorite.id model=model.favorite %}
    </td>
    <td>
      {% if is_editing %}
      <button unicorn:click="save">Save</button>
      <button unicorn:click.discard="cancel" unicorn:partial.key="{{ model.pk }}">Cancel</button>
      {% else %}
      <button unicorn:click="edit" unicorn:partial.key="{{ model.pk }}">Edit</button>
      {% endif %}
    </td>
</tr>

example/unicorn/templates/unicorn/nested/table.html
{% load unicorn %}
<div>
  <div>
    <button unicorn:click="$reset">$reset</button>
    <button unicorn:click="$refresh">$refresh</button>

    {% if is_editing %}
    <input type="text" unicorn:model.defer="name" />
    <button unicorn:click="save">Save</button>
    <button unicorn:click="cancel">Cancel</button>
    {% else %}
    <h3>{{ name }}</h3>
    <a href="#" unicorn:click.prevent="edit">Edit</a>
    {% endif %}
  </div>

  <button unicorn:click="load_table">Load table</button>

  <div>Favorite count: {{ favorite_count }}</div>

  <button u:click="show_filter=True">Show Filter</button>

  {% if show_filter %}
  {% unicorn 'nested.filter' %}
  {% endif %}

  <table>
    <thead>
      <tr>
        <td>Name</td>
        <td>Label</td>
        <td>Datetime</td>
        <td>Favorite</td>
        <td>Action</td>
      </tr>
    </thead>
    {% for flavor in flavors %}
    {% unicorn 'nested.row' key=flavor.id model=flavor %}
    {% endfor %}
  </table>

  <button unicorn:click="load_table">Load table</button>

</div>

example/unicorn/templates/unicorn/objects.html
<!-- test comment -->

<div>
  <div>
    <label>Dictionaries (original)</label>
    <input u:model="dictionary.name" type="text" id="dictionary">
    <input u:model="dictionary.nested.name" type="text" id="nestedDictionary">

    <br />
    dictionary.name: {{ dictionary.name }}<br />
    dictionary.nested.name: {{ dictionary.nested.name }}<br />
    <button u:click='set_dictionary({"name": 1, "nested": {"name": 2}})'>set dictionary 1,2</button>
    <button u:click='dictionary.nested.name=3'>set dictionary,nested.name=3</button>
    <button u:click.debounce-1000='set_dictionary({"name": 4, "nested": {"name": 5}})'>debounce set
      dictionary 4,5</button>
  </div>

  <div u:model="dictionary">
    <label>Dictionaries (model parent)</label>
    <input u:field="name" type="text" id="dictionary2">
    <input u:field="nested.name" type="text" id="nestedDictionary2">

    <br />
    dictionary.name: {{ dictionary.name }}<br />
    dictionary.nested.name: {{ dictionary.nested.name }}<br />
    <button u:click='set_dictionary({"name": 1, "nested": {"name": 2}})'>set dictionary(1)</button>
    <button u:click='dictionary.nested.name=3'>set dictionary(3)</button>
    <button u:click='set_dictionary_2'>set dictionary whoa</button>

    <div>
      {{ dictionary_2 }}
    </div>
  </div>

  <div>
    <label>Datetime</label>

    <div>
      {{ date_example }}
    </div>
    <div>
      <button u:click='get_date'>get_date</button>
      <button u:click='check_date("2020-09-12T01:01:01")'>check_date static string</button>
      <button u:click='check_date("{{ date_example|date:'c' }}")'>check_date (c)</button>
    </div>
  </div>

  <div>
    <label>Datetime with type hint</label>

    <div>
      {{ date_example_with_typehint }}
    </div>
    <div>
      <button u:click='check_date("{{ date_example_with_typehint|date:'c' }}")'>check_date (c)</button>
      <button u:click='check_date({{ date_example_with_typehint|date:'U' }})'>check_date (U)</button>
      <button u:click='add_hour()'>add_hour()</button>
    </div>
  </div>

  <div>
    <label>Datetimes in a list</label>

    <div>
      <div>Dates list with no type hint (will change to strings with an action)</div>
      <ul>
        {% for date in dates_with_no_typehint %}
        <li>{{ date }}</li>
        {% endfor %}
      </ul>

      <div>Dates list with just list type hint (will change to strings with an action)</div>
      <ul>
        {% for date in dates_with_list_typehint %}
        <li>{{ date }}</li>
        {% endfor %}
      </ul>

      <div>Dates list with old type hint (should stay datetimes with an action)</div>
      <ul>
        {% for date in dates_with_old_typehint %}
        <li>{{ date }}</li>
        {% endfor %}
      </ul>

      <div>Dates list with new type hint (should stay datetimes with an action)</div>
      <ul>
        {% for date in dates_with_new_typehint %}
        <li>{{ date }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div>
    <label>Pydantic field</label>
    <input u:model="pydantic_field.title" type="text" id="pydanticField">
    <input u:model="pydantic_field.publish_date" type="text" id="datetimePydanticField">

    <br />
    pydantic_field.title: {{ pydantic_field.title }}<br />
    pydantic_field.publish_date: {{ pydantic_field.publish_date }}<br />
  </div>

  <div>
    <label>Nested unicorn field property (original)</label>
    <input u:model="unicorn_field.title" type="text" id="unicornField">
    <input u:model="unicorn_field.publish_date_field.year" type="text" id="nestedUnicornField">
    <input u:model="unicorn_field.publish_date" type="text" id="nestedDatetimeUnicornField">

    <br />
    unicorn_field.title: {{ unicorn_field.title }}<br />
    unicorn_field.publish_date_field.year: {{ unicorn_field.publish_date_field.year }}<br />

    <br />
    <button
      u:click="unicorn_field={'title': 'title1', 'publish_date': 'blob', 'publish_date_field': {'year': 1999}}">Set with
      dictionary</button>
  </div>

  <div u:model="unicorn_field">
    <label>Nested unicorn field property (model parent)</label>
    <input u:field="title" type="text" id="unicornField2">
    <input u:field="publish_date_field.year" type="text" id="nestedUnicornField2">
    <input u:field="publish_date" type="text" id="nestedDatetimeUnicornField2">

    <br />
    unicorn_field.title: {{ unicorn_field.title }}<br />
    unicorn_field.publish_date_field.year: {{ unicorn_field.publish_date_field.year }}<br />

    <br />
    <button
      u:click="unicorn_field={'title': 'title1', 'publish_date': 'blob', 'publish_date_field': {'year': 1999}}">Set with
      dictionary</button>
  </div>

  <div>
    <label>Django models</label>
    <input u:model="book.title" type="text" id="bookId">

    <br />
    book.title: {{ book.title }} 📖
  </div>

  <div>
    <label>Django queryset (limited to readonly for now)</label>
    <input u:model="books.0.title" type="text" id="booksId" readonly>

    <br />
    Book queryset

    <ul>
      {% for b in books %}
      <li>Book in queryset: {{ b.title }}</li>
      {% endfor %}
    </ul>
  </div>

  <div>
    <input u:model="float_example" type="text" id="floatExampleId">
    <br />
    <input u:model="decimal_example" type="text" id="decimalExampleId">
    <br />
    <input u:model="int_example" type="text" id="intExampleId">
    <br />

    <button type="submit" u:click="add_one_to_float">Add 1 to float</button>
    <br />
    float_example: {{ float_example }}
    <br />
  </div>

  <div>
    <label>Enums</label>
    <br />

    <button unicorn:click="set_color({{ color.value }})">Sets color based on `self.color` enum</button>
    <button unicorn:click="set_color(2)">Sets `self.color` to `Color.GREEN`</button>
    <button unicorn:click="set_color({{ color.BLUE.value }})">Sets `self.color` to `Color.BLUE`</button>

    <br />
    color: {{ color }}
  </div>

  <div>
    <button u:click="$reset">$reset</button>
    <button u:click="$refresh">$refresh</button>
  </div>
</div>

example/unicorn/templates/unicorn/polling.html
<div unicorn:poll-1000="get_date" unicorn:poll.disable="polling_disabled">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div id="poll-id">
        poll-id: {{ current_time|date:"s" }}
    </div>

    current_time: {{ current_time|date:"s" }}

    <br /><br/>
    <button u:click="slow_update()">Increase counter: {{counter}}</button>

    <br /><br />
    <input unicorn:model="date_example" type="text" id="dateExampleId">
    date_example: {{ date_example }} | {{ date_example|date:"s" }}<br />

    <button u:click="polling_disabled=False">Enable Polling</button>
    <button u:click="polling_disabled=True">Disable Polling</button>
    <button u:click="$toggle('polling_disabled')">Toggle Polling</button>
</div>

example/unicorn/templates/unicorn/redirects.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

<div unicorn:view>
  <h2>Redirects</h2>

  <div>
    <a u:click="update_location">Update Location</a>
    <br />
    Current location count: {{ location_count }}
  </div>

  <div>
    <a u:click="update_hash">Update Hash</a>
    <br />
    Current hash count: {{ hash_count }}
  </div>

  <div>
    <a u:click="do_redirect">Redirect</a>
  </div>
</div>

{% endblock content %}

example/unicorn/templates/unicorn/test-datetime.html
{% load unicorn %}
<div>
  <div style="width:200px;height:200px;margin:10px;background-color:#aaffaa" unicorn:click="foo()">
    {{ dt }}<br>
    (click me)
  </div>
</div>

example/unicorn/templates/unicorn/todo.html
{% load static %}

<div>
    <div>{{ unicorn.errors.task.0.message }}</div>

    <div class="field has-addons">
        <p class="control">
            <form unicorn:submit.prevent="add">
                <input class="input" type="text" unicorn:model="task" unicorn:keydown.escape="task=''" placeholder="New task" id="task"></input>
            </form>
        </p>
        <p class="control">
            <span>
            <button unicorn:click="add" class="button is-info">Add</button>&nbsp;&nbsp;
            <button unicorn:click="$reset" class="button is-danger" {% if not tasks %}disabled{% endif %} style="border-radius: 4px;">Clear all tasks</button>
        </span>

            <span u:loading style="position: relative; left: 6px;">
                <img src="{% static 'svg/oval.svg' %}" style="vertical-align: middle;"></img>
            </span>
        </p>
    </div>

    <p>
        {% if tasks %}
        <ul>
            {% for task in tasks %}
            <li>{{ task }}</li>
            {% endfor %}
        </ul>
        {% else %}
        No tasks 🎉
        {% endif %}
    </p>
</div>

example/unicorn/templates/unicorn/wizard/step1.html
<div>
  <h3>Step 1</h3>

  <div>
    <input type="text" u:model="name" />
  </div>

  <div>
    Name: {{ name }}
  </div>

  <button unicorn:click="noop()">No-op</button>

  <button unicorn:click="$parent.next()">Next</button>
  <button unicorn:click="$parent.finish()">Finish</button>
</div>

example/unicorn/templates/unicorn/wizard/step2.html
<div>
  <div>Step 2</div>

  <div>
    <input u:model="address" />
    <input u:model="city" />
    <input u:model="state" />
    <input u:model="zip_code" />
  </div>

  <div>
    Address: {{ address }}<br />
    City: {{ city }}<br />
    State: {{ state }}<br />
    Zip code: {{ zip_code }}<br />
  </div>

  <button unicorn:click="$parent.previous()">Previous</button>
  <button unicorn:click="$parent.next()">Next</button>
</div>

example/www/templates/www/base.html
{% load static unicorn %}

<html>

<head>
  <title>django-unicorn examples</title>
  <link rel="stylesheet" href="{% static 'css/marx.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    #menu {
      list-style: none;
    }

    #menu li {
      display: inline;
      padding: 0 10px;
      border-left: solid 1px black;
    }

    #menu li:first-child {
      border-left: none !important;
    }

  </style>

  <script defer src="https://unpkg.com/@alpinejs/morph@3.x.x/dist/cdn.min.js"></script>
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>

  {% unicorn_scripts %}
</head>

<body>
  <main>
    {% csrf_token %}

    <h1>django-unicorn</h1>

    <ul id="menu">
      <li><a href="{% url 'www:index' %}">Index</a></li>
      <li><a href="{% url 'www:template' 'text-inputs' %}">Text inputs</a></li>
      <li><a href="{% url 'www:template' 'html-inputs' %}">HTML inputs</a></li>
      <li><a href="{% url 'www:template' 'objects' %}">Objects</a></li>
      <li><a href="{% url 'www:template' 'validation' %}">Validation</a></li>
      <li><a href="{% url 'www:template' 'polling' %}">Polling</a></li>
      <li><a href="{% url 'www:template' 'models' %}">Models</a></li>
      <li><a href="{% url 'www:template' 'nested' %}">Nested components (table)</a></li>
      <li><a href="{% url 'www:template' 'js' %}">JavaScript integration</a></li>
      <li><a href="{% url 'www:direct-view' %}">Direct View</a></li>
      <li><a href="{% url 'www:redirects' %}">Redirects</a></li>
      <li><a href="{% url 'www:template' 'wizard' %}">Wizard</a></li>
    </ul>

    {% block content %}{% endblock content %}

  </main>
</body>

</html>

example/www/templates/www/html-inputs.html
{% extends "www/base.html" %}
{% load unicorn %}

{% block content %}

<h2>HTML inputs</h2>

{% unicorn 'html-inputs' %}

{% unicorn 'todo' hello='world' %}

{% unicorn 'todo' hello=example %}

{% endblock content %}

example/www/templates/www/js.html
{% extends "www/base.html" %}
{% load static unicorn %}

{% block content %}

<h2>JavaScript integration</h2>

{% unicorn 'js' %}

{% endblock content %}